Js player card ids
Massey-7-Wonders-project-team/Massey_Project_7_Wonders pull request #26
Opened 2017-08-12 05:05 UTC by jacobstringer

Fixes a bug in the DB creation, includes a new cardhist class, for easy tracking of cards which have already been played, and updates several API calls to work with the newly created player id (which along with card id seek to simplify the PKs so less information needs passing back to the server and queries are simplified).

2017-08-12 05:08 UTC, mmdonaldson commented on application/cardhist.py
> +class Cardhist(db.Model):
Cardlist?

2017-08-12 05:09 UTC, mmdonaldson requested changes
Shouldn't these db models be merged with the other db models inside models?

2017-08-12 22:42 UTC, jacobstringer commented
Ugh - I thought I had uploaded them into the models folder. Good spotting - fixed now.

2017-08-13 02:53 UTC, mmdonaldson approved these changes

2017-08-13 02:53 UTC, merged